# Generated by Django 5.2.14 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_actividad_id_alter_clase_id_alter_profesor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='medio_pago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
