# Generated by Django 6.0.4 on 2026-06-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
