# Generated by Django 6.0.5 on 2026-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
