# Generated by Django 6.0.5 on 2026-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_reserva_estado_pago_reserva_medio_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='precio_clase',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='actividad',
            name='precio_mensualidad',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
    ]
