# Generated by Django 6.0.5 on 2026-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_reserva_asistio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='modalidad',
            field=models.CharField(choices=[('individual', 'Individual'), ('mensual', 'Mensual')], default='individual', max_length=10),
        ),
    ]
