# Generated by Django 6.0.4 on 2026-06-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_clase_cupo_maximo'),
        ('gestion', '0004_reserva_modalidad'),
    ]

    operations = [
    ]
