# Generated by Django 6.0.5 on 2026-05-21 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_clase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('usuario', 'clase', 'fecha_clase')},
        ),
    ]
