# Generated by Django 6.0.5 on 2026-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_profesor_correo_profesor_dni_profesor_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
