# Generated by Django 6.0.5 on 2026-05-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_initial'),
        ('gestion', '0006_profesor_fecha_nacimiento'),
    ]

    operations = [
    ]
