# Generated by Django 6.0.5 on 2026-07-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(choices=[('profesor_ausente', 'Profesor ausente'), ('feriado', 'Feriado'), ('problemas_climaticos', 'Problemas climáticos'), ('mantenimiento', 'Mantenimiento'), ('evento_especial', 'Evento especial'), ('otro', 'Otro')], max_length=50)),
                ('otro_motivo', models.CharField(blank=True, max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_suspension', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones', to='gestion.clase')),
            ],
            options={
                'unique_together': {('clase', 'fecha')},
            },
        ),
    ]
