# Generated by Django 6.0.5 on 2026-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_suspensionclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
