# Generated by Django 6.0.5 on 2026-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_clase_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='puede_confirmar',
            field=models.BooleanField(default=False),
        ),
    ]
