# Generated by Django 6.0.5 on 2026-06-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_actividad_id_alter_clase_id_alter_profesor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(default='clase', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='precio_clase',
            field=models.DecimalField(decimal_places=2, default=3500.0, max_digits=10),
        ),
    ]
