# Generated by Django 6.0.5 on 2026-07-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_reserva_puede_confirmar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='precio_mensualidad',
        ),
    ]
