# Generated by Django 6.0.4 on 2026-05-20 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('mercadopago', 'Mercado Pago')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('tipo', models.CharField(choices=[('clase', 'Inscripción a Clase Única'), ('mensualidad', 'Mensualidad de Actividad')], max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.actividad')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
