# Generated by Django 6.0.5 on 2026-06-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepto_declaracion_apto',
            field=models.BooleanField(default=False, verbose_name='Aceptó la declaración de responsabilidad del apto médico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_declaracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de la declaración'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_carga_apto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de carga del apto médico'),
        ),
    ]
