# Generated by Django 6.0.5 on 2026-07-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_acepto_declaracion_apto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Clase Individual'), ('mensual', 'Clase Mensual')], max_length=10)),
                ('fecha_falta', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strike',
                'verbose_name_plural': 'Strikes',
            },
        ),
    ]
