# Generated by Django 6.0.5 on 2026-05-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_id'),
        ('usuarios', '0003_usuario_reset_token_usuario_reset_token_expira_and_more'),
    ]

    operations = [
    ]
