# Generated by Django 6.0.5 on 2026-07-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='penalizacion_pendiente_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='penalizacion_pendiente_mensual',
            field=models.BooleanField(default=False),
        ),
    ]
