# Generated by Django 6.0.4 on 2026-06-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='gestion.actividad')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
            },
        ),
    ]
