# Generated by Django 6.0.5 on 2026-05-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0004_alter_actividad_id_alter_clase_id_alter_profesor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='gestion.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'unique_together': {('usuario', 'actividad', 'mes', 'anio')},
            },
        ),
    ]
