# Generated by Django 6.0.5 on 2026-07-01 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_voucher'),
        ('reservas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='gestion.clase'),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('usuario', 'clase', 'mes', 'anio')},
        ),
    ]
