# Generated by Django 6.0.5 on 2026-05-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_mensualidad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
